# Health level classification of students 

###  Nursery UCI Dataset is used for classification

If you download the dataset it doesn't have any column name and it is very messy so you should first clean the dataset as below:

At first we load the row data which we just downlaoded. 

In [6]:
import pandas as pd #we use pandas for data manipulation.

df = pd.read_csv('rawdata.csv')
df.head()

usual  proper  complete  1  convenient convenient.1        nonprob  \
0  usual  proper  complete  1  convenient   convenient        nonprob   
1  usual  proper  complete  1  convenient   convenient        nonprob   
2  usual  proper  complete  1  convenient   convenient  slightly_prob   
3  usual  proper  complete  1  convenient   convenient  slightly_prob   
4  usual  proper  complete  1  convenient   convenient  slightly_prob   

   recommended  recommend  
0     priority   priority  
1    not_recom  not_recom  
2  recommended  recommend  
3     priority   priority  
4    not_recom  not_recom

Now i am going to delete column with the name "1"

In [7]:
df.drop("1", axis = 1, inplace = True)

In [8]:
df.head()

usual  proper  complete  convenient convenient.1        nonprob  \
0  usual  proper  complete  convenient   convenient        nonprob   
1  usual  proper  complete  convenient   convenient        nonprob   
2  usual  proper  complete  convenient   convenient  slightly_prob   
3  usual  proper  complete  convenient   convenient  slightly_prob   
4  usual  proper  complete  convenient   convenient  slightly_prob   

   recommended  recommend  
0     priority   priority  
1    not_recom  not_recom  
2  recommended  recommend  
3     priority   priority  
4    not_recom  not_recom

Ok, now i set column to our data as follow:
I create a set of column and set it as column name:

In [9]:
column_list= ["parents","has_nurs","form","children","housing","finance","social","health"]
df.columns =column_list

In [10]:
df.head()

parents has_nurs      form    children     housing        finance  \
0   usual   proper  complete  convenient  convenient        nonprob   
1   usual   proper  complete  convenient  convenient        nonprob   
2   usual   proper  complete  convenient  convenient  slightly_prob   
3   usual   proper  complete  convenient  convenient  slightly_prob   
4   usual   proper  complete  convenient  convenient  slightly_prob   

        social     health  
0     priority   priority  
1    not_recom  not_recom  
2  recommended  recommend  
3     priority   priority  
4    not_recom  not_recom

now we have to change the data types for example parents column are string we dont want strings in our data set so we change it to one hot dataset as follow:

In [11]:
df.parents.value_counts()

pretentious    4320
great_pret     4320
usual          4319
Name: parents, dtype: int64

In [12]:
df_target = df.health

now we set out target we can remove it and create one-hot from other features to pass them for train process

In [14]:
df.drop("health", axis = 1, inplace = True)

In [16]:
df.head()

parents has_nurs      form    children     housing        finance  \
0   usual   proper  complete  convenient  convenient        nonprob   
1   usual   proper  complete  convenient  convenient        nonprob   
2   usual   proper  complete  convenient  convenient  slightly_prob   
3   usual   proper  complete  convenient  convenient  slightly_prob   
4   usual   proper  complete  convenient  convenient  slightly_prob   

        social  
0     priority  
1    not_recom  
2  recommended  
3     priority  
4    not_recom

As you see now we dont have health column now we make one-hot from other features

In [17]:
df_one_hot = pd.get_dummies(df)

In [18]:
df_one_hot.head()

parents_great_pret  parents_pretentious  parents_usual  has_nurs_critical  \
0                   0                    0              1                  0   
1                   0                    0              1                  0   
2                   0                    0              1                  0   
3                   0                    0              1                  0   
4                   0                    0              1                  0   

   has_nurs_improper  has_nurs_less_proper  has_nurs_proper  \
0                  0                     0                1   
1                  0                     0                1   
2                  0                     0                1   
3                  0                     0                1   
4                  0                     0                1   

   has_nurs_very_crit  form_complete  form_completed         ...          \
0                   0              1               0         ...           
1                   0              1               0         ...           
2                   0              1               0         ...           
3                   0              1               0         ...           
4                   0              1               0         ...           

   children_critical  children_less_conv  housing_convenient  housing_inconv  \
0                  0                   0                   1               0   
1                  0                   0                   1               0   
2                  0                   0                   1               0   
3                  0                   0                   1               0   
4                  0                   0                   1               0   

   finance_nonprob  finance_problematic  finance_slightly_prob  \
0                1                    0                      0   
1                1                    0                      0   
2                0                    0                      1   
3                0                    0                      1   
4                0                    0                      1   

   social_not_recom  social_priority  social_recommended  
0                 0                1                   0  
1                 1                0                   0  
2                 0                0                   1  
3                 0                1                   0  
4                 1                0                   0  

[5 rows x 23 columns]

OK, now we have a clean one hot matrix with "non" data we chack it again as follow:

In [20]:
missing_data = df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

parents
False    12959
Name: parents, dtype: int64

has_nurs
False    12959
Name: has_nurs, dtype: int64

form
False    12959
Name: form, dtype: int64

children
False    12959
Name: children, dtype: int64

housing
False    12959
Name: housing, dtype: int64

finance
False    12959
Name: finance, dtype: int64

social
False    12959
Name: social, dtype: int64



As you see all features are without non data so its great.

Now we try to concat data to prepare our dataset.

In [22]:
dataset = pd.concat([df_target,df_one_hot],axis = 1)

In [23]:
dataset.head()

health  parents_great_pret  parents_pretentious  parents_usual  \
0   priority                   0                    0              1   
1  not_recom                   0                    0              1   
2  recommend                   0                    0              1   
3   priority                   0                    0              1   
4  not_recom                   0                    0              1   

   has_nurs_critical  has_nurs_improper  has_nurs_less_proper  \
0                  0                  0                     0   
1                  0                  0                     0   
2                  0                  0                     0   
3                  0                  0                     0   
4                  0                  0                     0   

   has_nurs_proper  has_nurs_very_crit  form_complete         ...          \
0                1                   0              1         ...           
1                1                   0              1         ...           
2                1                   0              1         ...           
3                1                   0              1         ...           
4                1                   0              1         ...           

   children_critical  children_less_conv  housing_convenient  housing_inconv  \
0                  0                   0                   1               0   
1                  0                   0                   1               0   
2                  0                   0                   1               0   
3                  0                   0                   1               0   
4                  0                   0                   1               0   

   finance_nonprob  finance_problematic  finance_slightly_prob  \
0                1                    0                      0   
1                1                    0                      0   
2                0                    0                      1   
3                0                    0                      1   
4                0                    0                      1   

   social_not_recom  social_priority  social_recommended  
0                 0                1                   0  
1                 1                0                   0  
2                 0                0                   1  
3                 0                1                   0  
4                 1                0                   0  

[5 rows x 24 columns]

At last we just categorize targets .

In [24]:
dataset.replace("not_recom",0 ,inplace = True)
dataset.replace("priority",1 ,inplace = True)
dataset.replace("spec_prior",2 ,inplace = True)
dataset.replace("very_recom",3 ,inplace = True)
dataset.replace("recommend",4 ,inplace = True)

In [25]:
dataset.head()

health  parents_great_pret  parents_pretentious  parents_usual  \
0       1                   0                    0              1   
1       0                   0                    0              1   
2       4                   0                    0              1   
3       1                   0                    0              1   
4       0                   0                    0              1   

   has_nurs_critical  has_nurs_improper  has_nurs_less_proper  \
0                  0                  0                     0   
1                  0                  0                     0   
2                  0                  0                     0   
3                  0                  0                     0   
4                  0                  0                     0   

   has_nurs_proper  has_nurs_very_crit  form_complete         ...          \
0                1                   0              1         ...           
1                1                   0              1         ...           
2                1                   0              1         ...           
3                1                   0              1         ...           
4                1                   0              1         ...           

   children_critical  children_less_conv  housing_convenient  housing_inconv  \
0                  0                   0                   1               0   
1                  0                   0                   1               0   
2                  0                   0                   1               0   
3                  0                   0                   1               0   
4                  0                   0                   1               0   

   finance_nonprob  finance_problematic  finance_slightly_prob  \
0                1                    0                      0   
1                1                    0                      0   
2                0                    0                      1   
3                0                    0                      1   
4                0                    0                      1   

   social_not_recom  social_priority  social_recommended  
0                 0                1                   0  
1                 1                0                   0  
2                 0                0                   1  
3                 0                1                   0  
4                 1                0                   0  

[5 rows x 24 columns]

In [35]:
clean_dataste = dataset.to_csv("clean_data.csv")

##### OK Well done we cleaned the data and its prepare for training phase.

for classification there is many methods here i'm gonna use DNN method to classify any 5 groups.
I use keras for implementation.

/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Using TensorFlow backend.


In [3]:
!pip3 install keras-metrics

  Using cached https://files.pythonhosted.org/packages/86/54/a68c0b9cadca06c1a02b2d93bc4ab7b3ef5f805d28ee80467433a7da5139/keras_metrics-0.0.7-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/7b/74/54c5f9bb9bd4dae27a61ec1b39076a39d359b3fb7ba15da79ef23858a9d8/numpy-1.16.0-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/30/99/d7d4fbf2d02bb30fb76179911a250074b55b852d34e98dd452a9f394ac06/h5py-2.9.0-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/67/e6/6d4edaceee6a110ecf6f318482f5229792f143e468b34a631f5a0899f56d/scipy-1.2.0-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
  Using cached https://file

In [1]:
import tensorflow as tf
from keras.preprocessing import sequence
import time
from sklearn.metrics import classification_report
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Embedding
from keras.layers import LSTM
from sklearn.metrics import confusion_matrix, precision_score, recall_score, cohen_kappa_score
from keras.layers import Conv1D, MaxPooling1D
from keras.datasets import imdb
from sklearn import preprocessing
import pandas as pd
from keras.optimizers import SGD, Adam, Nadam, Adagrad
from sklearn.model_selection import StratifiedKFold
from keras.layers import BatchNormalization

from keras.layers import Dense, Dropout, LSTM, Embedding, Activation
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from keras.optimizers import SGD, Adam, Nadam
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score
from keras.utils.vis_utils import plot_model
from keras.layers.normalization import BatchNormalization
import keras
from keras import backend as K
import matplotlib.pyplot as plt
from keras.utils import to_categorical
from sklearn.preprocessing import MinMaxScaler
import keras_metrics
from sklearn.model_selection import StratifiedKFold
import time


/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Using TensorFlow backend.


In [6]:
#def load_data(input_file):
def train_evaluate(model, x_train, y_train, x_test, y_test):
    model.fit(x_train, y_train,batch_size=32, nb_epoch=1000)
    return model.evaluate(x_test, y_test)

df =pd.read_csv('clean_data.csv')

X = np.array(df.drop(['health'], 1)) 
df.dropna(inplace=True)
y = np.array(df['health'])


Y = to_categorical(y)
print(Y)
X_train, X_test, y_train, y_test =train_test_split (X, Y, test_size=0.2)


print("categorized target = ",Y)

print('y_test = ',y_test)

max_features = 1000000
maxlen = 202
embedding_size = 320






batch_size = 100


epochs = 1000


def create_model():
  # def create_model(input_length):
    print ('Creating model...')
    model = Sequential()
    model.add(BatchNormalization())
    model.add(Dense(512, input_dim=34, init='uniform'))
    model.add(Dropout(0.5))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(256, init='uniform'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(5, init='uniform'))
    model.add(Activation('softmax'))

    #sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
    #adam = Adam(lr=0.05)


    print ('Compiling...')
    
    
    model.compile(loss='categorical_crossentropy',
                  optimizer=Adam(lr=0.01, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False),
                  #metrics=['accuracy'])
                  metrics=['accuracy'])



  
    return model





print(X_train.shape)

model = create_model()

print ('Fitting model...')
history = model.fit(X_train, y_train, batch_size=1000, nb_epoch=100, validation_split = 0.1, verbose = 1)


# plt.show()
score, acc = model.evaluate(X_test, y_test, batch_size=100)
y_pred = model.predict(X_test)
print('acc = ', acc)
print(y_pred)
y_pred = (y_pred > 0.5) 


print(classification_report(y_test, y_pred))

print(y_pred)
model.summary()



[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
categorized target =  [[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
y_test =  [[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
(10367, 24)
Creating model...
Compiling...
Fitting model...


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:42: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(512, input_dim=34, kernel_initializer="uniform")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:47: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(256, kernel_initializer="uniform")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:51: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, kernel_initializer="uniform")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:80: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 9330 samples, validate on 1037 samples
Epoch 1/100
9330/9330 [==============================] - 2s 242us/step - loss: 0.5104 - acc: 0.8110 - val_loss: 0.2015 - val_acc: 0.9257
Epoch 2/100
9330/9330 [==============================] - 1s 57us/step - loss: 0.2167 - acc: 0.9074 - val_loss: 0.1635 - val_acc: 0.9248
Epoch 3/100
9330/9330 [==============================] - 1s 74us/step - loss: 0.1803 - acc: 0.9204 - val_loss: 0.1563 - val_acc: 0.9219
Epoch 4/100
9330/9330 [==============================] - 1s 74us/step - loss: 0.1676 - acc: 0.9272 - val_loss: 0.1359 - val_acc: 0.9354
Epoch 5/100
9330/9330 [==============================] - 1s 61us/step - loss: 0.1624 - acc: 0.9293 - val_loss: 0.1418 - val_acc: 0.9325
Epoch 6/100
9330/9330 [==============================] - 1s 74us/step - loss: 0.1523 - acc: 0.9316 - val_loss: 0.1313 - val_acc: 0.9315
Epoch 7/100
9330/9330 [==============================] - 1s 76us/step - loss: 0.1448 - acc: 0.9353 - val_loss: 0.1135 - val_acc: 0.9354

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


Thank you 
Good Luck!!!